#!/bin/bash

# Store the result of the `ls -la` command in a variable
ls_cwd_output=$(ls -la)

# Write the contents of the variable to the file ls_cwd_content
echo "$ls_cwd_output" > ls_cwd_content
#why?

